applications/persona/urls.py
from django.contrib import admin
from django.urls import path

# def desdePersona(self):
#     print('desde la app persona=====================')
    
# urlpatterns = [
#     path('persona/', desdePersona)
# ]
from . import views

app_name = "persona_app"

urlpatterns = [
    path( #url para pagina de inicio
        '',
        views.InicioView.as_view(),
        name='Inicio'
    ),
    path(
        'listar-todo-empleados/', 
        views.ListAllEmpleados.as_view(),
        name='empleados_all'
    ),
    path(
        'listar-by-area/<shortname>/', 
        views.ListByAreaEmpleados.as_view(),
        name='empleado_areas'
    ),
    path('buscar_empleado/', views.ListEmpleadosByKword.as_view()),
    path('lista_habilidades/', views.ListHabilidadesEmpleado.as_view()),
    path(
        'ver-empleado/<pk>', 
        views.EmpleadoDetailView.as_view(),
        name='empleado_detail'
    ),
    path(
        'add-empleado/', 
        views.EmpleadoCreateView.as_view(),
        name='empleado_add'
    ),
    path(
        'success/',
        views.SuccessView.as_view(),
        name='correcto'
    ),
    path(
        'update-empleado/<pk>',
        views.EmpleadoUpdateView.as_view(),
        name='modificar_empleado' #etiqueta
    ),
    path(
        'delete-empleado/<pk>',
        views.EmpleadoDeleteView.as_view(),
        name='eliminar_empleado' #etiqueta
    ),
    path(
        'lista-empleado-admin',
        views.ListEmpleadosAdmin.as_view(),
        name='empleado_admin' #etiqueta
    ),
]

empleados/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    #incluimos la urls de la app departamento
    re_path('', include('applications.departamento.urls')),
    re_path('', include('applications.persona.urls')),
    re_path('', include('applications.home.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/persona/models.py
from django.db import models
from applications.departamento.models import Departamento
from ckeditor.fields import RichTextField

class Habilidades(models.Model):
    habilidad = models.CharField('Habilidad', max_length=50)    

    class Meta:
        verbose_name = "Habilidades"
        verbose_name_plural = "Habilidadess"

    def __str__(self):
        return str(self.id) + '-' + self.habilidad


# Create your models here.
class Empleado(models.Model):
    """Modelo para tabla empleado"""
    
    JOB_CHOICES = (
        ('0', 'CONTADOR'),
        ('1', 'ADMINISTRADOR'),
        ('2', 'ECONOMISTA'),
        ('3', 'OTRO')
    )
    
    first_name = models.CharField('Nombres', max_length=60)
    last_name = models.CharField('apellidos', max_length=60)
    full_name = models.CharField(
        'Nombres Completos',
        max_length = 120,
        blank = True
    )
    job = models.CharField('Trabajo', max_length=1, choices=JOB_CHOICES)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE) #clave foranea
    avatar = models.ImageField(upload_to='empleado', blank=True, null=True)
    habilidades = models.ManyToManyField(Habilidades) # relacion de muchos a muchos
    hoja_de_vida = RichTextField()  #usando app de terceros, editor de texto
    
    class Meta:
        verbose_name = 'Area de Empleado' #cambia el nombre de un titulo en el administrador
        ordering = ['-id'] #ordena los items por nombre o segun el orden en la lista ['id', '-name']
        unique_together = ('first_name', 'last_name', 'job') # para no registrar datos repetidos
        
    def __str__(self):
        return str(self.id) + '-' + self.first_name + '-' + self.last_name

applications/persona/forms.py
from django import forms
from .models import Empleado

class EmpleadoForm(forms.ModelForm):
    
    class Meta:
        model = Empleado
        fields = (
            "first_name",
            "last_name",
            "job",
            "departamento",
            "avatar",
            "habilidades",
        )
        widgets = {
            'habilidades': forms.CheckboxSelectMultiple()
        }

applications/persona/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    TemplateView,
    UpdateView,
    DeleteView
)
from .models import Empleado
#Importa los campos de forms.py de la app
from .forms import EmpleadoForm
# Create your views here.


class InicioView(TemplateView):
    """Vista que carga la pagina de inicio"""
    template_name = 'inicio.html'
    
class ListAllEmpleados(ListView):
    """
    Lista todos los empleados
    """
    template_name = 'persona/list_all.html'
    paginate_by = 4 #paginacion para limitar la cantidad de datos a mostrar
    ordering = 'first_name'
    # model = Empleado
    context_object_name = 'empleados'
    
    def get_queryset(self):
        palabra_clave = self.request.GET.get("kword", "")
        lista = Empleado.objects.filter(
            full_name__icontains=palabra_clave #icontains busca segun los caracteres que se escriba
        )
        return lista
    
class ListEmpleadosAdmin(ListView):
    """
    Lista todos los empleados
    """
    template_name = 'persona/lista_empleado.html'
    paginate_by = 4 #paginacion para limitar la cantidad de datos a mostrar
    ordering = 'id'
    # model = Empleado
    context_object_name = 'empleados'
    model = Empleado


class ListByAreaEmpleados(ListView):
    """
    Lista empleados por departamento
    """
    template_name = 'persona/list_by_area.html'
    context_object_name = 'empleados'
    # queryset = Empleado.objects.filter(
    #     departamento__name = 'Otro'
    # )
    def get_queryset(self):
        area = self.kwargs['shortname']
        lista = Empleado.objects.filter(
            # departamento__name = 'Otro'
            departamento__name = area
        )
        return lista

class ListEmpleadosByKword(ListView):
    """
    Lista Empleados por palabra clave
    """
    template_name = 'persona/by_kword.html'
    context_object_name = 'empleados'
    
    def get_queryset(self):
        palabra_clave = self.request.GET.get("kword", "")
        lista = Empleado.objects.filter(
            # departamento__name = 'Otro'
            first_name = palabra_clave
        )
        print(lista)
        return lista

class ListHabilidadesEmpleado(ListView):
    """
    Lista las habilidades
    """
    template_name = 'persona/habilidades.html'
    context_object_name = 'habilidades'
    
    def get_queryset(self):
        palabra_clave = self.request.GET.get("kword", "")    
        print(palabra_clave)
        if palabra_clave == '':
            return []
        else:
            empleado = Empleado.objects.get(id=palabra_clave)
            return empleado.habilidades.all()


class EmpleadoDetailView(DetailView):
    model = Empleado
    template_name = "persona/detail_empleado.html"
    
    def get_context_data(self, **kwargs):
        context = super(EmpleadoDetailView, self).get_context_data(**kwargs)
        context["titulo"] = 'Empleado del Mes'
        return context


class SuccessView(TemplateView): #Es un template basico Emite un mensaje
    template_name = "persona/success.html"

class EmpleadoCreateView(CreateView):
    model = Empleado
    template_name = "persona/add.html"
    form_class = EmpleadoForm
    # fields = ['first_name', 'last_name', 'job', 'departamento', 'habilidades', 'avatar'] # carga los campos selecionados para el formulario
    # fields = ('__all__')# carga todos los campos
    # success_url = '.' #Para que redireccione a la misma pagina despues de presionar el btn agregar
    # success_url = '/success' #Redirecciona a success.html
    success_url = reverse_lazy('persona_app:empleado_admin') #metodo de django para redirecionar
    
    def form_valid(self, form):
        empleado = form.save(commit=False) #asigna todos los valores guardados del formulario en la variable empleado
        empleado.full_name = empleado.first_name + " " + empleado.last_name
        empleado.save()
        return super(EmpleadoCreateView, self).form_valid(form)


class EmpleadoUpdateView(UpdateView):
    model = Empleado
    template_name = "persona/update.html"
    fields = ['first_name', 'last_name', 'job', 'departamento', 'habilidades', 'avatar']
    success_url = reverse_lazy('persona_app:empleado_admin') #metodo de django para redirecionar despues de hacer un post
    
    def post(self, request, *args, **kwargs): # podemos usar metodo post para guardar datos antes de ser validados por el form_valid que POST se ejecuta primero
        """
        request pueder ser usado para recuperar datos enviado por el POST
        """
        self.object = self.get_object()
        # print(request.POST)
        # print(request.POST['last_name'])
        return super().post(request, *args, **kwargs)
    
    # def form_valid(self, form): #
    #     return super(EmpleadoCreateView, self).form_valid(form)


class EmpleadoDeleteView(DeleteView):
    model = Empleado
    template_name = "persona/delete.html"
    success_url = reverse_lazy('persona_app:empleado_admin') #metodo de django para redirecionar

templates/persona/add.html
{% extends 'base.html' %}
<!-- {{object_list}} -->

{% block title %}
Nuevo Empleado
{% endblock title %}

{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell" style="text-align: center;">Registrar Nuevo Empleado</h1>
        <div class="cell">
            <form class="grid-x grid-margin-x" action="" method="POST" enctype="multipart/form-data"> {% csrf_token %}
                <div class="cell large-6">
                    <label>Nombres:
                        {{form.first_name}}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Apellido:
                        {{form.last_name}}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Trabajo:
                        {{form.job}}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Departamento:
                        {{form.departamento}}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Habilidades:
                        {{form.habilidades}}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Foto:
                        {{form.avatar}}
                    </label>
                </div>
                <div class="cell">
                    <button class="button success" type="submit">Guardar</button>
                </div>
                
                
            </form>
        </div>
    </div>
</div>
{% endblock content%}

<h1>Registrar Persona</h1>
<form action="" method="POST"> {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Agregar</button>
</form>

templates/persona/by_kword.html
<h1>Buscar Empleados por Kword</h1>

<form action="" method="GET">{% csrf_token %}
    <input type="text" name="kword" id="kword" placeholder="Ingrese nombre aqui">
    <button type="submit">Buscar</button>
</form>

<h3>Lista Resultados</h3>
<ul>
    
    {% for e in empleados %}
        <li>{{e}}</li>
    {% endfor %}
        
</ul>

templates/persona/delete.html
{% extends 'base.html' %}
<!-- {{object_list}} -->

{% block title %}
Eliminar Empleado
{% endblock title %}

{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell" style="text-align: center;">Eliminar datos del Empleado {{ object.full_name }}</h1>
        <form class="cell grid-margin-x" action="" method="POST"> {% csrf_token %}
            <div class="callout alert">
                <p class="cell">Confirme que desea Eliminar</p>
                <button class="button alert" type="submit">Confirmar</button>    
            </div>   
        </form>
    </div>
</div>
{% endblock content%}

templates/persona/detail_empleado.html
{% extends 'base.html' %}
<!-- {{object_list}} -->
{% load static %}
{% block title %}
{{ object.full_name }}
{% endblock title %}

{% block content %}

{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x" align-center>
        <div class="cell small-3 large-6 card" style="width: 300px; margin-top: 10px">
            <div class="card-divider">
                {{ empleado.get_job_display }}
            </div>
            
            {% if empleado.avatar %}
            <img src="{{ empleado.avatar.url }}">
            {% else %}
            <img src="{% static 'img/img1.jpg' %}">
            {% endif %}
                
            
            <div class="card-section">
                <h4>{{ empleado.full_name }}</h4>
                <p>{{empleado.first_name}}</p>
                <p>{{empleado.last_name}}</p>
                <p>{{empleado.departamento.short_name}}</p>
                <p><span class="label">Habilidades</span></p>
                <ul class="vertical menu">                    
                    {% for h in empleado.habilidades.all %}
                        <li> {{ h.habilidad }} </li>
                    {% endfor %}                        
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/persona/habilidades.html
<h1>Habilidades de Empleados</h1>
<form action="" method="GET">{% csrf_token %}
    <input type="text" name="kword" id="kword" placeholder="Ingrese Habilidad aqui">
    <button type="submit">Buscar</button>
</form>
<ul>
    
    {% for e in habilidades %}
        <li>{{e}}</li>
    {% endfor %}
        
</ul>

templates/persona/list_all.html
{% extends 'base.html' %}
<!-- {{object_list}} -->

{% block title %}
Lista Empleados
{% endblock title %}

{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell" style="text-align: center;">Lista de todos los Empleados</h1>

        <!-- Inicio de buscar -->
        <form class="cell grid-x grid-margin-x" method="GET"> {% csrf_token %}
            <div class="cell large-7">
                <input type="text" name="kword" id="kword" placeholder="Buscar Empleado">
            </div>
            <div class="cell large-2">
                <button type="submit" class="success button">Buscar</button>
            </div>
        </form>
        <!-- Fin de Buscar -->

        <!-- Inicio de tabla -->
        <div class="cell">
            <table>
                <thead>
                    <tr>
                        <th width="200">ID</th>
                        <th>Nombres</th>
                        <th width="150">Apellidos</th>
                        <th width="150">Departamento</th>
                        <th width="150">Accion</th>
                    </tr>
                </thead>
                <tbody>
                    {% for e in empleados %}
                    <tr>
                        <td>{{ e.id }}</td>
                        <td>{{ e.first_name }}</td>
                        <td>{{ e.last_name }}</td>
                        <td>{{ e.departamento }}</td>
                        <td><a class="button warning" href="{% url 'persona_app:empleado_detail' e.id %}">Ver</a></td>
                    </tr>
                    {% endfor %}

                </tbody>
            </table>
        </div>
        <!--Fin de tabla -->
        <!-- Inicio de paginacion -->
        <div class="cell">            
            {% if is_paginated %}
                <nav aria-label="Pagination">
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                        <li class="pagination-previous">
                            <a href="?page={{ page_obj.previous_page_number }}">Atras</a>
                        </li>
                        {% endif %}
                        
                        {% for pagina in paginator.page_range %}                        
                            {% ifequal pagina page_obj.number  %} 
                                <li class="current"><span class="show-for-sr">You're on page</span>{{ pagina }}</li>
                            {% else %}
                                <li><a href="?page={{pagina}}">{{ pagina }}</a></li>                                
                            {% endifequal %}                            
                        {% endfor %}
                            
                        {% if page_obj.has_next %}                        
                        <li class="pagination-next">
                            <a href="?page={{ page_obj.next_page_number }}">Siguiente</a>
                        </li>
                        {% endif %}
                    </ul>
                </nav>
            {% endif %}
        </div>        
    </div>
    <!-- Fin de paginacion -->
    <!-- Inicio de paginacion -->

    <!-- <div class="grid-x pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div> -->
    <!-- Fin de paginacion -->
</div>
{% endblock content %}

templates/persona/list_by_area.html
{% extends 'base.html' %}


{% block title %}
    Lista de empleado por departamento
{% endblock title %}
    

{% block content %}
    {% include "includes/header.html" %}
    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell" style="text-align: center;">Lista empleados por Departamento</h1>    
            <!-- Inicio de tabla -->
            <div class="cell">
                <table>
                    <thead>
                        <tr>
                            <th width="200">ID</th>
                            <th>Nombres</th>
                            <th width="150">Apellidos</th>
                            <th width="150">Departamento</th>
                            <th width="150">Accion</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for e in empleados %}
                        <tr>
                            <td>{{ e.id }}</td>
                            <td>{{ e.first_name }}</td>
                            <td>{{ e.last_name }}</td>
                            <td>{{ e.departamento }}</td>
                            <td><a class="button warning" href="{% url 'persona_app:empleado_detail' e.id %}">Ver</a></td>
                        </tr>
                        {% endfor %}
    
                    </tbody>
                </table>
            </div>
            <!--Fin de tabla -->
            <!-- Inicio de paginacion -->
            <div class="cell">            
                {% if is_paginated %}
                    <nav aria-label="Pagination">
                        <ul class="pagination">
                            {% if page_obj.has_previous %}
                            <li class="pagination-previous">
                                <a href="?page={{ page_obj.previous_page_number }}">Atras</a>
                            </li>
                            {% endif %}
                            
                            {% for pagina in paginator.page_range %}                        
                                {% ifequal pagina page_obj.number  %} 
                                    <li class="current"><span class="show-for-sr">You're on page</span>{{ pagina }}</li>
                                {% else %}
                                    <li><a href="?page={{pagina}}">{{ pagina }}</a></li>                                
                                {% endifequal %}                            
                            {% endfor %}
                                
                            {% if page_obj.has_next %}                        
                            <li class="pagination-next">
                                <a href="?page={{ page_obj.next_page_number }}">Siguiente</a>
                            </li>
                            {% endif %}
                        </ul>
                    </nav>
                {% endif %}
            </div>        
        </div>
{% endblock content %}
    

<!-- {{object_list}} -->

templates/persona/lista_empleado.html
{% extends 'base.html' %}
<!-- {{object_list}} -->

{% block title %}
Lista Empleados
{% endblock title %}

{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell" style="text-align: center;">Lista de todos los Empleados</h1>
        <!-- Inicio de tabla -->
        <div class="cell">
            <table>
                <thead>
                    <tr>
                        <th width="200">ID</th>
                        <th>Nombres</th>
                        <th width="150">Apellidos</th>
                        <th width="150">Departamento</th>
                        <th width="150">Accion</th>
                    </tr>
                </thead>
                <tbody>
                    {% for e in empleados %}
                    <tr>
                        <td>{{ e.id }}</td>
                        <td>{{ e.first_name }}</td>
                        <td>{{ e.last_name }}</td>
                        <td>{{ e.departamento }}</td>
                        <td>
                            <a class="button primary" href="{% url 'persona_app:modificar_empleado' e.id %}">Editar</a>
                        </td>
                        <td>
                            <a class="button alert" href="{% url 'persona_app:eliminar_empleado' e.id %}">Eliminar</a>
                        </td>
                    </tr>
                    {% endfor %}

                </tbody>
            </table>
        </div>
        <!--Fin de tabla -->
        <!-- Inicio de paginacion -->
        <div class="cell">            
            {% if is_paginated %}
                <nav aria-label="Pagination">
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                        <li class="pagination-previous">
                            <a href="?page={{ page_obj.previous_page_number }}">Atras</a>
                        </li>
                        {% endif %}
                        
                        {% for pagina in paginator.page_range %}                        
                            {% ifequal pagina page_obj.number  %} 
                                <li class="current"><span class="show-for-sr">You're on page</span>{{ pagina }}</li>
                            {% else %}
                                <li><a href="?page={{pagina}}">{{ pagina }}</a></li>                                
                            {% endifequal %}                            
                        {% endfor %}
                            
                        {% if page_obj.has_next %}                        
                        <li class="pagination-next">
                            <a href="?page={{ page_obj.next_page_number }}">Siguiente</a>
                        </li>
                        {% endif %}
                    </ul>
                </nav>
            {% endif %}
        </div>        
    </div>
</div>
{% endblock content %}

templates/persona/success.html
<h1>Felicitacion se guardo correctamente</h1>

templates/persona/update.html
{% extends 'base.html' %}
<!-- {{object_list}} -->

{% block title %}
Editar Empleado
{% endblock title %}

{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Modificar datos de Empleado</h1>
        <div class="cell">
            <form class="grid-x grid-margin-x" action="" method="POST" enctype="multipart/form-data"> {% csrf_token %}
                <div class="cell large-6">
                    <label>Nombres:
                        {{form.first_name}}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Apellido:
                        {{form.last_name}}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Trabajo:
                        {{form.job}}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Departamento:
                        {{form.departamento}}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Habilidades:
                        {{form.habilidades}}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Foto:
                        {{form.avatar}}
                    </label>
                </div>
                <div class="cell">
                    <button class="button success" type="submit">Guardar</button>
                </div>
                
                
            </form>
        </div>
    </div>
</div>
{% endblock content%}