applications/departamento/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "departamento_app"
urlpatterns = [
    path(
        'new_departamento/', 
        views.NewDepartamentoView.as_view(), 
        name='nuevo_departamento'
    ),
    path(
        'departamento-lista/', 
        views.DepartamentoListView.as_view(), 
        name='departamento_list'
    ),
]

applications/persona/urls.py
from django.contrib import admin
from django.urls import path

# def desdePersona(self):
#     print('desde la app persona=====================')
    
# urlpatterns = [
#     path('persona/', desdePersona)
# ]
from . import views

app_name = "persona_app"

urlpatterns = [
    path( #url para pagina de inicio
        '',
        views.InicioView.as_view(),
        name='Inicio'
    ),
    path(
        'listar-todo-empleados/', 
        views.ListAllEmpleados.as_view(),
        name='empleados_all'
    ),
    path(
        'listar-by-area/<shortname>/', 
        views.ListByAreaEmpleados.as_view(),
        name='empleado_areas'
    ),
    path('buscar_empleado/', views.ListEmpleadosByKword.as_view()),
    path('lista_habilidades/', views.ListHabilidadesEmpleado.as_view()),
    path(
        'ver-empleado/<pk>', 
        views.EmpleadoDetailView.as_view(),
        name='empleado_detail'
    ),
    path(
        'add-empleado/', 
        views.EmpleadoCreateView.as_view(),
        name='empleado_add'
    ),
    path(
        'success/',
        views.SuccessView.as_view(),
        name='correcto'
    ),
    path(
        'update-empleado/<pk>',
        views.EmpleadoUpdateView.as_view(),
        name='modificar_empleado' #etiqueta
    ),
    path(
        'delete-empleado/<pk>',
        views.EmpleadoDeleteView.as_view(),
        name='eliminar_empleado' #etiqueta
    ),
    path(
        'lista-empleado-admin',
        views.ListEmpleadosAdmin.as_view(),
        name='empleado_admin' #etiqueta
    ),
]

empleados/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    #incluimos la urls de la app departamento
    re_path('', include('applications.departamento.urls')),
    re_path('', include('applications.persona.urls')),
    re_path('', include('applications.home.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/departamento/models.py
from django.db import models

# Create your models here.
class Departamento(models.Model):
    name = models.CharField('Nombre', max_length=100)
    short_name = models.CharField('Nombre Corto', max_length=20, unique=True)
    anulate = models.BooleanField('Anulado', default=False)
    
    class Meta:
        verbose_name = 'Mi Departamento' #cambia el nombre de un titulo en el administrador
        verbose_name_plural = 'Areas de la empresa'
        ordering = ['-name'] #ordena los items por nombre o segun el orden en la lista ['id', '-name']
        unique_together = ('name', 'short_name') # para no registrar datos repetidos
        
    def __str__(self):
        return str(self.id) + '-' + self.name + '-' + self.short_name

applications/departamento/forms.py
from django import forms

class NewDepartamentoForm(forms.Form):
    """
    Creando formulario que no se realaciona a ningun modelo(BD)
    """
    nombre = forms.CharField(max_length=50)
    apellido = forms.CharField(max_length=50)
    departamento = forms.CharField(max_length=50)
    short = forms.CharField(max_length=20)

applications/departamento/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.edit import FormView
from django.views.generic import ListView
from .forms import NewDepartamentoForm

from applications.persona.models import Empleado
from .models import Departamento
# Create your views here.

class DepartamentoListView(ListView):
    model = Departamento
    template_name = "Departamento/lista.html"
    context_object_name = 'departamentos'


class NewDepartamentoView(FormView):
    """
    Crea un nuevo dpto
    """
    template_name = 'departamento/new_departamento.html'
    form_class = NewDepartamentoForm
    success_url = '/'
    
    def form_valid(self, form):
        depa = Departamento(
            name = form.cleaned_data['departamento'],
            short_name = form.cleaned_data['short']
        )
        depa.save()
        
        nombre = form.cleaned_data['nombre']
        apellido = form.cleaned_data['apellido']
        Empleado.objects.create(
            first_name = nombre,
            last_name = apellido,
            job = '1',
            departamento = depa
        )
        return super(NewDepartamentoView, self).form_valid(form)

templates/departamento/lista.html
{% extends 'base.html' %}


{% block title %}
    Lista Departamentos
{% endblock title %}


{% block content %}
    {% include "includes/header.html" %}

    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell" style="text-align: center;">Lista Departamento</h1>
            <div class="cell">
                <table>
                    <tbody>
                        
                        {% for departamento in departamentos %}
                        <tr>
                            <td>{{departamento.name}}</td>
                            <td>{{departamento.short_name}}</td>                           
                            <td>
                                <a class="button warning" href="{% url 'persona_app:empleado_areas' departamento.short_name %}">Ver Empleados</a>
                            </td>
                        </tr>
                        {% endfor %}
                            
                        
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    
{% endblock content %}
    

templates/departamento/new_departamento.html
{% extends 'base.html' %}
<!-- {{object_list}} -->

{% block title %}
Nuevo Departamento
{% endblock title %}

{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell" style="text-align: center;">Registrar Nuevo Departamento</h1>
        <div class="cell">
            <form class="grid-x callout grid-margin-x" action="" method="POST" enctype="multipart/form-data"> {% csrf_token %}
                <div class="cell large-6">
                    <label>Nombres:
                        {{form.nombre}}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Apellido:
                        {{form.apellido}}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Departamento:
                        {{form.departamento}}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Nombre Corto:
                        {{form.short}}
                    </label>
                </div>
                <div class="cell">
                    <button class="button primary" type="submit">Guardar</button>
                </div>
                
                
            </form>
        </div>
    </div>
</div>
{% endblock content%}

<h1>Registrar Persona</h1>
<form action="" method="POST"> {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Agregar</button>
</form>
<h1>Registrar Nuevo Departamento</h1>
<form action="" method="post"> {% csrf_token %}
    <h3>Datos Empleados</h3>
    <p>{{form.nombre}}</p>
    <p>{{form.apellido}}</p>
    <h3>Datos del Departamento</h3>
    <p>{{form.departamento}}</p>
    <p>{{form.short}}</p>
    <button type="submit">Guardar</button>
</form>